services:
  - type: web
    name: notes-backend
    env: node
    repo: https://github.com/Jule1097/notes-app/tree/main
    branch: users-notes
    buildCommand: npm ci
    startCommand: npm run start:prod
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
databases:
  - name: notes-db
    engine: postgresql
    version: "14"
    plan: starter